version: 0.1
log:
  fields:
    service: registry

storage:
  filesystem:
    rootdirectory: /var/lib/registry

http:
  addr: :5000
  headers:
    Access-Control-Allow-Origin: ['http://192.168.68.64:8080']
    Access-Control-Allow-Methods: ['HEAD', 'GET', 'OPTIONS', 'DELETE']
    Access-Control-Allow-Headers: ['Authorization', 'Accept', 'Cache-Control', 'Range']
    Access-Control-Expose-Headers: ['Docker-Content-Digest']
